name: Build Android version

on: [push]

jobs:
  build:
    name: Build and create release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Packages
      run: |
          sudo apt -y install git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          sudo apt install cython3
          sudo apt update
          sudo apt install build-essential
          sudo apt install libstdc++6
          sudo apt install aidl
    - name: Symlink cython3 to cython
      run: |
          sudo ln -s /usr/bin/cython3 /usr/local/bin/cython    

    - name: Run build.sh (DEBUG)
      run: |
        rm ./.buildozer -rf
        rm ~/.buildozer -rf
        chmod a+x build.sh

        ./build.sh debug
        echo "Listing all files recursively (inc. hidden files) - DEBUG"
        ls -Ra 
        
 #       echo "Attempting to copy *.apk to ./"
 #       cp bin/*.apk ./equationBuddy_DEBUG.apk
 #   - name: Upload apk to git
 #     run: |
 #       git config --global user.email "ryandobson@duck.com"
 #       git config --global user.name "TmDobbin"
 #       git add bin/
 #       git commit -m "Auto Build apk"
 #       git push -u origin main
    #/equationBuddy_DEBUG.apk
    - name: Checkout code
      uses: actions/checkout@v2
   # - name: Create Release
   #   id: create_release
   #   uses: actions/create-release@v1
   #   env:
   #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   #   with:
   #     tag_name: debug_apk
   #     release_name: Autobuild ${{ github.ref }}
   #     body: Auto build of the android package *.apk
   #     file: bin/*.apk
   #     draft: false
   #     prerelease: true
        
    - name: Create Release and Upload Files
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "debug_apk"
        prerelease: true
        title: "APK Autobuild"
        files: |
          bin/*.apk
      
 
