name: Build Android version

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Packages
      run: |
          sudo apt -y install git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          sudo apt install cython3
          sudo apt update
          sudo apt install build-essential
          sudo apt install libstdc++6
          sudo apt install aidl
    - name: Symlink cython3 to cython
      run: |
          sudo ln -s /usr/bin/cython3 /usr/local/bin/cython    

    - name: Run build.sh (DEBUG)
      run: |
        rm ./.buildozer -rf
        rm ~/.buildozer -rf
        chmod a+x build.sh

        ./build.sh debug
    - name: Upload apk to git
      run: |
        git add bin/
        git commit -m "Auto Build apk"
        git push -u origin main
      
        
 
