name: Build Android version

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Packages
      run: |
          sudo apt install cython3
          sudo apt install aidl
    - name: Symlink cython3 to cython
      run: |
          sudo ln -s /usr/bin/cython3 /usr/local/bin/cython    

    - name: Run build.sh (DEBUG)
      run: |
        chmod a+x build.sh

        ./build.sh debug
 
