name: Build Android version

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: List files
      run: |
        chmod a+x build.sh
        ./build.sh
 
